### ISSUE TITLE
Hi i downloaded it and installed but on plex it keeps saying channel not available check url and i tried all the urls im running windows 10 plex 

### ISSUE THREAD

**Issue by ghost** [coder-alpha/CcloudTv.bundle#3] opened 2015-09-18 00:55 UTC

**Comment by coder-alpha** [comment] 2015-09-18 01:54
Please read and follow direction from post 1 & 2 located here https://forums.plex.tv/discussion/166602/rel-ccloudtv-channel-iptv. If you are still facing issues feel free to report either on the Plex forum or here with some further details like url you are using etc. If the above solves your issues please close this issue. Thanks !

Cheers,
CA

**Comment by raymo967** [comment] 2015-09-18 02:15
http://pastebin.com/raw.php?i=TPg1MJ7c  use this for the url

**Comment by ghost** [comment] 2015-09-18 20:02
@raymo967 it saved but still get url error and im sorry @coder-alpha I dont quite understand your posts they confused me?

**Comment by ghost** [comment] 2015-09-18 21:35
also where is the channel prefs field of plugin found i think i might not be entering the info in the right spot

**Comment by meat-ball** [comment] 2015-09-19 12:05
hes suggesting you read the setup details laid out in the plex forums (the link) before posting an issue on github. this is for specific issues related with the plugin.

**Comment by coder-alpha** [comment] 2015-09-19 21:40
http://forums.plex.tv/discussion/comment/951877/#Comment_951877

**Comment by ghost** [comment] 2015-09-20 16:58
no matter what url i do i tried them all and yes @meat-ball i read all instructions but the fucking plex says channel url not found im really frustrated i ditched my cable for this :(

**Comment by ghost** [comment] 2015-09-20 16:58
no matter if i try on my roku or pc it still does not work i tried uninstall/reinstall\

**Comment by meat-ball** [comment] 2015-09-20 20:33
Right- Plex forums, post specifics as far as what you've filled in the plugin preferences so someone can identify Where the problem is. i can take a look in a few

**Comment by coder-alpha** [comment] 2015-09-20 20:58
@moosesenpai I'd like to help but the lack of information you are providing does not help in diagnosing the issue.
Please share a screen shot of your cCloud Channel Preferences and the error message you are receiving.

**Comment by ghost** [comment] 2015-09-21 00:57
@coder-alpha https://gyazo.com/20eae138bbe552ee48c90499008a6519
Thats the settings on my plex hope it helps

**Comment by coder-alpha** [comment] 2015-09-21 01:05
Ok, so now where it says cCloud TV (database) url paste this one
_http://pastebin.com/raw.php?i=pEh1qXiV_
then exit out of the cCloud App and then go back in. You should now see listing of 16 channels. Once you have this working you can substitute the link with the one posted above by raymo and do same.

Let me know.

**Comment by ghost** [comment] 2015-09-22 20:15
@coder-alpha Nope it still says no channels from both links

**Comment by coder-alpha** [comment] 2015-09-23 00:49
@moosesenpai This is not helpful in diagnosing the issue. Please include the exact error message, screenshots are helpful. And also include the log file for the channel. com.plexapp.plugins.ccloudtv.log found here C:\Users[User]\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs. You can send the log file by email if you would like to keep it private.

**Comment by ghost** [comment] 2015-09-23 23:10
@coder-alpha what is your email

**Comment by ghost** [comment] 2015-09-26 22:55
The exact error message is this:
No Channels Available. Please check website URL under Channel Preferences !

and this is the url i put in the url area
1;Updated:8/28-NDTV;News;India;English;http://ndtv.live-s.cdn.bitgravity.com/cdn-live-b7/_definst_/ndtv/live/ndtv247live.smil/playlist.m3u8|| 2;Updated:8/28-Bloomberg;News;US;English;http://cdn3.videos.bloomberg.com/btv/us/master.m3u8|| 3;Updated:8/28-Nasa TV;News;US;English;http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8|| 4;Updated:8/28-VEVO 1 HD;Music;US;English;http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/06/prog_index.m3u8|| 5;Updated:8/28-VEVO 2 HD;Music;US;English;http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch2/06/prog_index.m3u8|| 6;Updated:8/28-VEVO 3 HD;Music;US;English;http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch3/06/prog_index.m3u8|| 7;Updated:8/28-Russia Today;News;Russia;English;http://rt-a.akamaihd.net/ch_04@325608/720p.m3u8|| 8;Updated:8/28-Now Music;Music;US;English;http://rrr.sz.xlcdn.com/?account=AATW&file=nowmusic&type=live&service=wowza&protocol=http&output=playlist.m3u8|| 9;Updated:8/28-Big Bunny Video (1920x1080 30fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4|| 10;Updated:8/28-Big Bunny Video (1920x1080 60fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4|| 11;Updated:8/28-Big Bunny Video (4K 3840x2160 30fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_30fps_normal.mp4|| 12;Updated:8/28-Big Bunny Video (4K 3840x2160 60fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4|| 13;Updated:8/28-Big Bunny Video (3D 1920x1080 30fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_stereo_abl.mp4|| 14;Updated:8/28-Big Bunny Video (3D 1920x1080 60fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_stereo_abl.mp4|| 15;Updated:8/28-Big Bunny Video (3D 4K 3840x2160 30fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_30fps_stereo_abl.mp4|| 16;Updated:8/28-Big Bunny Video (3D 4K 4000x2250 60fps);MovieVideo;US;English;http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_native_60fps_stereo_abl.mp4

**Comment by coder-alpha** [comment] 2015-09-26 23:09
You dont put the content of the link in that field. You just need to put <h2>http://pastebin.com/raw.php?i=pEh1qXiV</h2>

**Comment by ghost** [comment] 2015-09-26 23:14
yeah i realized thanks anyways

**Comment by ghost** [comment] 2015-09-26 23:15
You can remove this issue

**Comment by coder-alpha** [comment] 2015-09-27 04:14
Closed !

**Closed as completed by coder-alpha** 2015-09-27 04:14 UTC
